apiVersion: apps/v1
kind: Deployment
metadata:
  name: locations-frontend
spec:
  selector:
    matchLabels:
      app: locations-frontend
  template:
    metadata:
      labels:
        app: locations-frontend
    spec:
      containers:
      - name: locations-frontend
        image: locations-frontend:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
