apiVersion: apps/v1
kind: Deployment
metadata:
  name: on-call-developer-api
  namespace: locations-app
spec:
  
  selector:
    matchLabels:
      app: on-call-developer-api
  replicas: 1
  template:
    metadata:
      labels:
        app: on-call-developer-api
    spec:
      containers:
      - name: on-call-developer-api
        image: on-call-developer-api:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
